============================================================
ESG
============================================================
### @name ESG：没有filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/esg_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query":"如何减排二氧化碳？", "topK": 3, "extK": 2}'

### @name ESG：没有filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/esg_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --data '{"query":"如何减排二氧化碳？", "topK": 3, "extK": 2}'

### @name ESG：rec_id_filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/esg_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query": "溫室氣體總排放量是多少？", "filter": {"rec_id": ["73338fdb-5c79-44fb-adbf-09f2b580acc8","07aba0bb-ac7c-41a2-b50b-d2f7793e5b3c"]}, "topK": 3}'

### @name ESG：时间filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/esg_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query": "溫室氣體總排放量是多少？", "datefilter": {"publication_date": {"gte": 1677836800}}, "topK": 3}'

### @name ESG：meta_contains
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/esg_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query": "溫室氣體總排放量是多少？", "meta_contains":"太古", "topK": 3}'

### @name ESG：remote
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/esg_search' \
    --header 'Authorization: Bearer {{$dotenv REMOTE_BEARER_TOKEN}}' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query": "溫室氣體總排放量是多少？", "filter": {"rec_id": ["73338fdb-5c79-44fb-adbf-09f2b580acc8","07aba0bb-ac7c-41a2-b50b-d2f7793e5b3c"]}, "extK": 2}'

### @name ESG：没有filter
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/esg_search' \
    --header 'Authorization: Bearer {{$dotenv REMOTE_BEARER_TOKEN}}' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"如何减排二氧化碳？", "topK": 3, "extK": 2}'

============================================================
Standard
============================================================
### @name Standard：时间和meta_contains_filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/standard_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query": "二氧化硫一级浓度限值是多少？", "datefilter": {"effective_date": {"gte": 1077836800}},"meta_contains":"钢铁 大气","topK": 3}'

### @name Standard：时间filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/standard_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query": "二氧化硫一级浓度限值是多少？", "datefilter": {"effective_date": {"gte": 1377836800}},"topK": 3}'

### @name Standard：标准号filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/standard_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query": "二氧化硫一级浓度限值是多少？", "filter": {"standard_number": ["HJ 1131-2020", "HJ 57-2017"]},"topK": 3}'

### @name Standard：meta_contains
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/standard_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query": "二氧化硫一级浓度限值是多少？", "meta_contains":"空气", "topK": 3}'

### @name Standard：没有filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/standard_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query": "二氧化硫一级浓度限值是多少？","topK": 3}'

### @name Standard：x-api-key
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/standard_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --data '{"query": "二氧化硫一级浓度限值是多少？","topK": 3}'

### @name Standard：扩展
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/standard_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query": "二氧化硫一级浓度限值是多少？","topK": 3, "extK": 2}'

### @name Standard：remote
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/standard_search' \
    --header 'Authorization: Bearer {{$dotenv REMOTE_BEARER_TOKEN}}' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"二氧化硫一级浓度限值是多少？","topK": 3, "extK": 2}'

### @name Standard：remote,x-api-key
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/standard_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"二氧化硫一级浓度限值是多少？","topK": 3, "extK": 2}'

============================================================
Internal
============================================================
### @name Internal_search：没有filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/internal_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query":"闲鱼如何减排二氧化碳？", "topK": 1}'

### @name Internal_search：x-api-key
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/internal_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --data '{"query":"闲鱼如何减排二氧化碳？", "topK": 1}'

### @name Internal_search：id_filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/internal_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query":"闲鱼如何减排二氧化碳？", "filter": {"rec_id": ["1722c59d-adda-4a1a-afd2-d656c1ef60bb","d878ab2b-17a5-4b71-a101-f9013a564309"]}, "topK": 3}'

### @name Internal_search：tag_filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/internal_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query":"闲鱼如何减排二氧化碳？", "filter": {"tag": ["ali"]}, "topK": 3}'

### @name Internal_search：扩展
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/internal_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query":"闲鱼如何减排二氧化碳？", "filter": {"tag": ["ali"]}, "topK": 3, "extK": 2}'

### @name Internal_search：remote
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/internal_search' \
    --header 'Authorization: Bearer {{$dotenv REMOTE_BEARER_TOKEN}}' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"闲鱼如何减排二氧化碳？", "topK": 3, "extK": 2}'

### @name Internal_search：remote,x-api-key
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/internal_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"闲鱼如何减排二氧化碳？", "topK": 3, "extK": 2}'

============================================================
TextBook
============================================================
### @name TextBook：local
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/textbook_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query":"如何减排二氧化碳？", "filter": {"isbn_number": ["9787030641274"]},"topK": 1, "extK": 1}'

### @name TextBook：remote
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/textbook_search' \
    --header 'Authorization: Bearer {{$dotenv REMOTE_BEARER_TOKEN}}' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"如何减排二氧化碳？", "filter": {"isbn_number": ["9787030641274"]},"topK": 1, "extK": 1}'

### @name TextBook：remote,x-api-key
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/textbook_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"如何减排二氧化碳？", "filter": {"isbn_number": ["9787030641274"]},"topK": 1, "extK": 1}'


============================================================
Edu
============================================================
### @name edu：local
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/edu_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query":"what is the relationship between filter layer expansion and washing intensity?", "filter": {"course": ["水处理工程","大气污染控制工程"]},"topK": 1, "extK": 1}'

### @name edu：local
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/edu_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query":"what is the relationship between filter layer expansion and washing intensity?", "topK": 5}'

### @name edu：local, x-api-key
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/edu_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --data '{"query":"what is the relationship between filter layer expansion and washing intensity?", "topK": 5}'

### @name edu：remote
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/edu_search' \
    --header 'Authorization: Bearer {{$dotenv REMOTE_BEARER_TOKEN}}' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"what is the relationship between filter layer expansion and washing intensity?","topK": 10}'

### @name edu：remote,x-api-key
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/edu_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"what is the relationship between filter layer expansion and washing intensity?","topK": 10}'


============================================================
SCI
============================================================
### @name SCI—local：没有filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/sci_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query":"关键金属物质流的全球贸易特征是什么?", "topK": 5}'

### @name SCI—local：没有filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/sci_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --data '{"query":"关键金属物质流的全球贸易特征是什么?", "topK": 5}'

### @name SCI—local：扩展
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/sci_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query":"关键金属物质流的全球贸易特征是什么?", "topK": 3, "extK": 2}'

### @name SCI—local：journal_filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/sci_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query":"关键金属物质流的全球贸易特征是什么?", "filter": {"journal": ["JOURNAL OF INDUSTRIAL ECOLOGY"]},"topK": 1}'

### @name SCI：complete_metadata
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/sci_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query":"关键金属物质流的全球贸易特征是什么?", "datefilter": {"date": {"gte": 1262304000}},"topK": 1, "getMeta": true}'

### @name SCI—remote：没有filter
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/sci_search' \
    --header 'Authorization: Bearer {{$dotenv REMOTE_BEARER_TOKEN}}' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"关键金属物质流的全球贸易特征是什么?", "topK": 5}'


### @name SCI—remote：x-api-key
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/sci_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"关键金属物质流的全球贸易特征是什么?", "topK": 5}'

============================================================
Report  
============================================================
### @name report—local：没有filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/report_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query":"coastal floods and sandy coastline recession are projected to increase?", "topK": 3, "extK": 2}'

### @name report—local：x-api-key
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/report_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --data '{"query":"coastal floods and sandy coastline recession are projected to increase?", "topK": 3, "extK": 2}'

### @name report—remote：x-api-key
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/report_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query": "coastal floods and sandy coastline recession are projected to increase?", "topK": 1}'


============================================================
Patent
============================================================
### @name patent—local：没有filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/patent_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query": "Tunnel for high-speed vehicles?", "topK": 1}'

### @name patent—local：x-api-key
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/patent_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --data '{"query": "Tunnel for high-speed vehicles?", "topK": 1}'


### @name patent—local：country_filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/patent_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query": "Tunnel for high-speed vehicles?", "filter": {"country": ["Japan"]}, "topK": 1}'

### @name patent—local：time_filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/patent_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query": "Tunnel for high-speed vehicles?", "datefilter": {"publication_date": {"gte": 1262304000}}, "topK": 3}'

### @name patent—remote：没有filter
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/patent_search' \
    --header 'Authorization: Bearer {{$dotenv REMOTE_BEARER_TOKEN}}' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query": "Tunnel for high-speed vehicles?", "topK": 1}'


### @name patent—remote：x-api-key
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/patent_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query": "Tunnel for high-speed vehicles?", "topK": 1}'

============================================================
Internet
============================================================
### @name internet—local
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/internet_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query":"哪些公司使用了阿里云来帮助减排？", "maxResults": 2}'

### @name internet—local:x-api-key
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/internet_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --data '{"query":"哪些公司使用了阿里云来帮助减排？", "maxResults": 2}'


### @name internet—remote
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/internet_search' \
    --header 'Authorization: Bearer {{$dotenv REMOTE_BEARER_TOKEN}}' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"哪些公司使用了阿里云来帮助减排？", "maxResults": 2}'


### @name internet—remote,x-api-key
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/internet_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"哪些公司使用了阿里云来帮助减排？", "maxResults": 2}'

============================================================
Edu Graph Search
============================================================
### @name edu—graph—local
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/edu_graph_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query":"大气污染控制", "root": 1, "depth": 1}'

### @name edu—graph—local：x-api-key
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/edu_graph_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --data '{"query":"大气污染控制", "root": 1, "depth": 1}'

### @name edu—graph—remote
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/edu_graph_search' \
    --header 'Authorization: Bearer {{$dotenv REMOTE_BEARER_TOKEN}}' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"大气污染控制", "root": 1, "depth": 2}'

### @name edu—graph—remote,x-api-key
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/edu_graph_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"大气污染控制", "root": 1, "depth": 2}'

============================================================
Tavily Search
============================================================
### @name tavily—search—local
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/tavily_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query":"哪些公司使用了阿里云来帮助减排？", "maxResults": 1}'

### @name tavily—search—local，x-api-key
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/tavily_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --data '{"query":"哪些公司使用了阿里云来帮助减排？", "maxResults": 1}'


### @name tavily—search—remote
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/tavily_search' \
    --header 'Authorization: Bearer {{$dotenv REMOTE_BEARER_TOKEN}}' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"哪些公司使用了阿里云来帮助减排？", "maxResults": 2}'

### @name tavily—search—remote
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/tavily_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"哪些公司使用了阿里云来帮助减排？", "maxResults": 2}'

============================================================
Tavily Extract
============================================================
### @name tavily—extract—local
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/tavily_extract' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"urls":"[\"https://www.baidu.com\",\"https://www.163.com\"]"}'

### @name tavily—extract—local,x-api-key
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/tavily_extract' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --data '{"urls":"[\"https://www.baidu.com\",\"https://www.163.com\"]"}'


### @name tavily—extract—remote
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/tavily_extract' \
    --header 'Authorization: Bearer {{$dotenv REMOTE_BEARER_TOKEN}}' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"urls":"[\"https://www.baidu.com\",\"https://www.163.com\"]"}'

### @name tavily—extract—remote,x-api-key
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/tavily_extract' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"urls":"[\"https://www.baidu.com\",\"https://www.163.com\"]"}'

============================================================
Edu Graph Generate
============================================================
### @name edu-graph-generate_
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/edu_graph_generate' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query":"海岸带资源环境调控", "root": 1, "depth": 2}'

### @name edu-graph-generate_：local,x-api-key
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/edu_graph_generate' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --data '{"query":"海岸带资源环境调控", "root": 1, "depth": 2}'

### @name edu-graph-generate_
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/edu_graph_generate' \
    --header 'Authorization: Bearer {{$dotenv REMOTE_BEARER_TOKEN}}' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"海岸带资源环境调控", "root": 1, "depth": 2}'

### @name edu-graph-generate_,x-api-key
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/edu_graph_generate' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"海岸带资源环境调控", "root": 1, "depth": 2}'


============================================================
Green_Deal_Search
============================================================
### @name green_deal_search：没有filter
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/green_deal_search' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --data '{"query":"欧盟新电池法规和循环经济行动计划有什么关系？", "topK": 1}'

### @name green_deal_search-api-key
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/green_deal_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --data '{"query":"欧盟新电池法规和循环经济行动计划有什么关系？", "topK": 1, "extK": 1}'

### @name green_deal_search：remote
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/green_deal_search' \
    --header 'Authorization: Bearer {{$dotenv REMOTE_BEARER_TOKEN}}' \
    --header 'Content-Type: application/json' \
    --header 'email: {{$dotenv EMAIL}}' \
    --header 'password: {{$dotenv PASSWORD}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"欧盟新电池法规和循环经济行动计划有什么关系？", "topK": 3, "extK": 2}'

### @name green_deal_search：remote,x-api-key
curl -i --location --request POST '{{$dotenv REMOTE_ENDPOINT}}/green_deal_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --header 'x-region: {{$dotenv X_REGION}}' \
    --data '{"query":"欧盟新电池法规和循环经济行动计划有什么关系？", "topK": 3, "extK": 2}'


============================================================
Bigquery_Search
============================================================
### @name Bigquery_Search：local,x-api-key
curl -i --location --request POST '{{$dotenv LOCAL_ENDPOINT}}/bigquery_search' \
    --header 'Content-Type: application/json' \
    --header 'x-api-key: {{$dotenv X_API_KEY}}' \
    --data '{"query":"欧盟新电池法规和循环经济行动计划有什么关系？"}'
